Ngq v2
safeh2o/swot-web-app pull request #88
Opened 2022-10-25 00:50 UTC by bhekuwenza

@moselhy faq list updated

2022-10-29 15:18 UTC, bhekuwenza commented
heey @moselhy please review this pull request

2022-10-30 23:36 UTC, moselhy commented
![image](https://user-images.githubusercontent.com/22180044/198907443-76a71183-eee9-4be5-84a9-99fd13f6ed0a.png)
![image](https://user-images.githubusercontent.com/22180044/198907448-82896129-8556-4dcd-8735-5313f7042001.png)

The sign-in button at the top right changes when hovered over, is that intentional?

2022-10-31 02:33 UTC, bhekuwenza commented
@moselhy pushed fix

2022-11-02 23:50 UTC, moselhy requested changes

2022-11-02 23:50 UTC, moselhy commented on client/src/components/tool/CollectData.jsx
> +													src={"#"}
check image src

2022-11-02 23:50 UTC, moselhy commented on client/public/index.html
>  <!DOCTYPE html>
revert this file

2022-11-02 23:50 UTC, moselhy commented on client/src/components/FAQ.jsx
> +						{/* <div className="FAQs-count small">
revert from here down

2022-11-02 23:50 UTC, moselhy commented on client/src/components/elements/NotificationLine.jsx
> +				{props?.tip?.context === "icon" ? iconElement : props?.children}
revert this file

2022-11-02 23:50 UTC, moselhy commented on client/src/components/layout/Header.jsx
> +			{/* <Grid
add back banner/popup

2022-11-02 23:50 UTC, moselhy commented on server/package-lock.json
> -		"node_modules/@sindresorhus/is": {
revert this file

2022-11-07 14:05 UTC, bhekuwenza commented on client/public/index.html
>  <!DOCTYPE html>
@moselhy I think you should revert this, and I will pull. I did edit this file

2022-11-07 14:07 UTC, bhekuwenza commented on client/src/components/layout/Header.jsx
> +			{/* <Grid
Launch is tomorrow. Will not need banner for this.

2022-11-07 14:25 UTC, bhekuwenza commented on client/public/index.html
>  <!DOCTYPE html>
Looks like an indentation issue actually.

2022-11-08 04:50 UTC, merged